version: '3'

services:
  authentication_jwt:
    image: mysql:latest
    container_name: authentication_jwt
    environment:
      MYSQL_DATABASE: authentication_jwt
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '9001:3306'
    volumes:
      - ./database:/var/lib/mysql
